### ISSUE TITLE
pg gem build fails on Chef Client 11.14.2

### ISSUE THREAD

**Issue by infinite-tape** [sous-chefs/postgresql#168]
Since upgrading to Chef Client 11.14.2, the postgresql::ruby recipe fails to build for me (worked great yesterday on Chef Client 11.12.8).

It appears that the rescue clause in ruby.rb is looking for Gem::Installer::ExtensionBuildError during pg gem build, but on the new version of chef I'm seeing the error as Mixlib::ShellOut::ShellCommandFailed (see log below). Built fine in an identical EC2 environment and AMI with Chef Client 11.12.8. Under that version, the error threw ExtensionBuildError, which was caught and forced to build (second code snippet).

I've used the same run list with `knife ec2 --bootstrap-version 11.12.8` and everything builds great on Ubuntu 14.04 ([ami-dc5387bf](http://cloud-images.ubuntu.com/trusty/20140801/)).

```
 Recipe: postgresql::ruby
   * chef_gem[pg] action install

     ================================================================================
     Error executing action `install` on resource 'chef_gem[pg]'
     ================================================================================

     Mixlib::ShellOut::ShellCommandFailed
     ------------------------------------
     Expected process to exit with [0], but received '1'
     ---- Begin output of /opt/chef/embedded/bin/gem install pg -q --no-rdoc --no-ri -v "0.17.1" ----
     STDOUT: Building native extensions.  This could take a while...
     STDERR: ERROR:  Error installing pg:
        ERROR: Failed to build gem native extension.

             /opt/chef/embedded/bin/ruby extconf.rb
     checking for pg_config... yes
     Using config values from /usr/bin/pg_config
     checking for libpq-fe.h... yes
     checking for libpq/libpq-fs.h... yes
     checking for pg_config_manual.h... yes
     checking for PQconnectdb() in -lpq... no
     checking for PQconnectdb() in -llibpq... no
     checking for PQconnectdb() in -lms/libpq... no
     Can't find the PostgreSQL client library (libpq)
     *** extconf.rb failed ***
     Could not create Makefile due to some reason, probably lack of
     necessary libraries and/or headers.  Check the mkmf.log file for more
     details.  You may need configuration options.

     Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/chef/embedded/bin/ruby
        --with-pg
        --without-pg
        --with-pg-config
        --without-pg-config
        --with-pg_config
        --without-pg_config
        --with-pg-dir
        --without-pg-dir
        --with-pg-include
        --without-pg-include=${pg-dir}/include
        --with-pg-lib
        --without-pg-lib=${pg-dir}/lib
        --with-pqlib
        --without-pqlib
        --with-libpqlib
        --without-libpqlib
        --with-ms/libpqlib
        --without-ms/libpqlib


     Gem files will remain installed in /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/pg-0.17.1 for inspection.
     Results logged to /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/pg-0.17.1/ext/gem_make.out
     ---- End output of /opt/chef/embedded/bin/gem install pg -q --no-rdoc --no-ri -v "0.17.1" ----
     Ran /opt/chef/embedded/bin/gem install pg -q --no-rdoc --no-ri -v "0.17.1" returned 1

     Cookbook Trace:
     ---------------
     /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:58:in `rescue in from_file'
     /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:24:in `from_file'
     /var/chef/cache/cookbooks/database/recipes/postgresql.rb:20:in `from_file'
     /var/chef/cache/cookbooks/server-cookbook/recipes/postgres.rb:13:in `from_file'
     /var/chef/cache/cookbooks/server-cookbook/recipes/default.rb:16:in `from_file'

     Resource Declaration:
     ---------------------
     # In /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb

      58:     chef_gem "pg"
      59:   rescue Gem::Installer::ExtensionBuildError => e

     Compiled Resource:
     ------------------
     # Declared in /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:58:in `rescue in from_file'

     chef_gem("pg") do
       provider Chef::Provider::Package::Rubygems
       action :install
       retries 0
       retry_delay 2
       guard_interpreter :default
       package_name "pg"
       version "0.17.1"
       timeout 900
       gem_binary "/opt/chef/embedded/bin/gem"
       cookbook_name "postgresql"
       recipe_name "ruby"
     end


   ================================================================================
   Recipe Compile Error in /var/chef/cache/cookbooks/server-cookbook/recipes/default.rb
   ================================================================================

   Mixlib::ShellOut::ShellCommandFailed
   ------------------------------------
   chef_gem[pg] (postgresql::ruby line 58) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
   ---- Begin output of /opt/chef/embedded/bin/gem install pg -q --no-rdoc --no-ri -v "0.17.1" ----
   STDOUT: Building native extensions.  This could take a while...
   STDERR: ERROR:  Error installing pg:
    ERROR: Failed to build gem native extension.

           /opt/chef/embedded/bin/ruby extconf.rb
   checking for pg_config... yes
   Using config values from /usr/bin/pg_config
   checking for libpq-fe.h... yes
   checking for libpq/libpq-fs.h... yes
   checking for pg_config_manual.h... yes
   checking for PQconnectdb() in -lpq... no
   checking for PQconnectdb() in -llibpq... no
   checking for PQconnectdb() in -lms/libpq... no
   Can't find the PostgreSQL client library (libpq)
   *** extconf.rb failed ***
   Could not create Makefile due to some reason, probably lack of
   necessary libraries and/or headers.  Check the mkmf.log file for more
   details.  You may need configuration options.

   Provided configuration options:
    --with-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/opt/chef/embedded/bin/ruby
    --with-pg
    --without-pg
    --with-pg-config
    --without-pg-config
    --with-pg_config
    --without-pg_config
    --with-pg-dir
    --without-pg-dir
    --with-pg-include
    --without-pg-include=${pg-dir}/include
    --with-pg-lib
    --without-pg-lib=${pg-dir}/lib
    --with-pqlib
    --without-pqlib
    --with-libpqlib
    --without-libpqlib
    --with-ms/libpqlib
    --without-ms/libpqlib


   Gem files will remain installed in /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/pg-0.17.1 for inspection.
   Results logged to /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/pg-0.17.1/ext/gem_make.out
   ---- End output of /opt/chef/embedded/bin/gem install pg -q --no-rdoc --no-ri -v "0.17.1" ----
   Ran /opt/chef/embedded/bin/gem install pg -q --no-rdoc --no-ri -v "0.17.1" returned 1

   Cookbook Trace:
   ---------------
     /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:58:in `rescue in from_file'
     /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:24:in `from_file'
     /var/chef/cache/cookbooks/database/recipes/postgresql.rb:20:in `from_file'
     /var/chef/cache/cookbooks/server-cookbook/recipes/postgres.rb:13:in `from_file'
     /var/chef/cache/cookbooks/server-cookbook/recipes/default.rb:16:in `from_file'

   Relevant File Content:
   ----------------------
   /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:

    51:    end
    52:  
    53:    node['postgresql']['client']['packages'].each do |pg_pack|
    54:      resources("package[#{pg_pack}]").run_action(:install)
    55:    end
    56:  
    57:    begin
    58>>     chef_gem "pg"
    59:    rescue Gem::Installer::ExtensionBuildError => e
    60:      # Are we an omnibus install?
    61:      raise if RbConfig.ruby.scan(%r{(chef|opscode)}).empty?
    62:      # Still here, must be omnibus. Lets make this thing install!
    63:      Chef::Log.warn 'Failed to properly build pg gem. Forcing properly linking and retrying (omnibus fix)'
    64:      gem_dir = e.message.scan(%r{will remain installed in ([^ ]+)}).flatten.first
    65:      raise unless gem_dir
    66:      gem_name = File.basename(gem_dir)
    67:      ext_dir = File.join(gem_dir, 'ext')


   Running handlers:
 [2014-08-02T00:45:04+00:00] ERROR: Running exception handlers
   Running handlers complete
 [2014-08-02T00:45:04+00:00] ERROR: Exception handlers complete
 [2014-08-02T00:45:04+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
   Chef Client failed. 13 resources updated in 120.81222453 seconds
 [2014-08-02T00:45:04+00:00] ERROR: chef_gem[pg] (postgresql::ruby line 58) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
 ---- Begin output of /opt/chef/embedded/bin/gem install pg -q --no-rdoc --no-ri -v "0.17.1" ----
 STDOUT: Building native extensions.  This could take a while...
 STDERR: ERROR:  Error installing pg:
    ERROR: Failed to build gem native extension.

         /opt/chef/embedded/bin/ruby extconf.rb
 checking for pg_config... yes
 Using config values from /usr/bin/pg_config
 checking for libpq-fe.h... yes
 checking for libpq/libpq-fs.h... yes
 checking for pg_config_manual.h... yes
 checking for PQconnectdb() in -lpq... no
 checking for PQconnectdb() in -llibpq... no
 checking for PQconnectdb() in -lms/libpq... no
 Can't find the PostgreSQL client library (libpq)
 *** extconf.rb failed ***
 Could not create Makefile due to some reason, probably lack of
 necessary libraries and/or headers.  Check the mkmf.log file for more
 details.  You may need configuration options.

 Provided configuration options:
    --with-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/opt/chef/embedded/bin/ruby
    --with-pg
    --without-pg
    --with-pg-config
    --without-pg-config
    --with-pg_config
    --without-pg_config
    --with-pg-dir
    --without-pg-dir
    --with-pg-include
    --without-pg-include=${pg-dir}/include
    --with-pg-lib
    --without-pg-lib=${pg-dir}/lib
    --with-pqlib
    --without-pqlib
    --with-libpqlib
    --without-libpqlib
    --with-ms/libpqlib
    --without-ms/libpqlib


 Gem files will remain installed in /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/pg-0.17.1 for inspection.
 Results logged to /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/pg-0.17.1/ext/gem_make.out
 ---- End output of /opt/chef/embedded/bin/gem install pg -q --no-rdoc --no-ri -v "0.17.1" ----
 Ran /opt/chef/embedded/bin/gem install pg -q --no-rdoc --no-ri -v "0.17.1" returned 1
 [2014-08-02T00:45:04+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
#### Relevant snippet from 11.12.8 (by forcing version with `--bootstrap-version`)

```
 Recipe: postgresql::ruby
   * chef_gem[pg] action install
 ================================================================================
 Error executing action `install` on resource 'chef_gem[pg]'
 ================================================================================


 Gem::Installer::ExtensionBuildError
 -----------------------------------
 ERROR: Failed to build gem native extension.

         /opt/chef/embedded/bin/ruby extconf.rb
 checking for pg_config... yes
 Using config values from /usr/bin/pg_config
 checking for libpq-fe.h... yes
 checking for libpq/libpq-fs.h... yes
 checking for pg_config_manual.h... yes
 checking for PQconnectdb() in -lpq... no
 checking for PQconnectdb() in -llibpq... no
 checking for PQconnectdb() in -lms/libpq... no
 Can't find the PostgreSQL client library (libpq)
 *** extconf.rb failed ***
 Could not create Makefile due to some reason, probably lack of
 necessary libraries and/or headers.  Check the mkmf.log file for more
 details.  You may need configuration options.

 Provided configuration options:
    --with-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/opt/chef/embedded/bin/ruby
    --with-pg
    --without-pg
    --with-pg-config
    --without-pg-config
    --with-pg_config
    --without-pg_config
    --with-pg-dir
    --without-pg-dir
    --with-pg-include
    --without-pg-include=${pg-dir}/include
    --with-pg-lib
    --without-pg-lib=${pg-dir}/lib
    --with-pqlib
    --without-pqlib
    --with-libpqlib
    --without-libpqlib
    --with-ms/libpqlib
    --without-ms/libpqlib


 Gem files will remain installed in /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/pg-0.17.1 for inspection.
 Results logged to /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/pg-0.17.1/ext/gem_make.out



 Cookbook Trace:
 ---------------
 /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:58:in `rescue in from_file'
 /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:24:in `from_file'
 /var/chef/cache/cookbooks/database/recipes/postgresql.rb:20:in `from_file'
 /var/chef/cache/cookbooks/server-cookbook/recipes/postgres.rb:13:in `from_file'
 /var/chef/cache/cookbooks/server-cookbook/recipes/default.rb:16:in `from_file'


 Resource Declaration:
 ---------------------
 # In /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb

  58:     chef_gem "pg"
  59:   rescue Gem::Installer::ExtensionBuildError => e



 Compiled Resource:
 ------------------
 # Declared in /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:58:in `rescue in from_file'

 chef_gem("pg") do
   provider Chef::Provider::Package::Rubygems
   action :install
   retries 0
   retry_delay 2
   guard_interpreter :default
   package_name "pg"
   version "0.17.1"
   cookbook_name "postgresql"
   recipe_name "ruby"
 end

 [2014-08-01T16:07:14+00:00] WARN: Failed to properly build pg gem. Forcing properly linking and retrying (omnibus fix)
   * execute[generate pg gem Makefile] action run
     - execute PATH=$PATH:/usr/pgsql-9.3/bin /opt/chef/embedded/bin/ruby extconf.rb

   * execute[make pg gem lib] action run
     - execute make

   * execute[install pg gem lib] action run
     - execute make install

   * execute[install pg spec] action run
     - execute /opt/chef/embedded/bin/gem spec ./cache/pg-0.17.1.gem --ruby > ./specifications/pg-0.17.1.gemspec

 [2014-08-01T16:07:27+00:00] WARN: Installation of pg gem successful!
```

**Comment by germs12** [comment]
@slyness This worked for me (to use the supermarket version), but seems to be broken in master.  I encountered the issue using the github version, but resolved w/ the supermarket version (`depends 'postgresql', '~> 3.4.18'`)
