### ISSUE TITLE
Centos7 Postgres 9.3 - initdb command does not work via systemd

### ISSUE THREAD

**Issue by erichelgeson** [sous-chefs/postgresql#186]
It appears you can not run the initdb via the service in Centos7 - 

```
[vagrant@java-app-centos-70 log]$ sudo /sbin/service postgresql-9.3 initdb
The service command supports only basic LSB actions (start, stop, restart, try-restart, reload, force-reload, status). For other actions, please try to use systemctl.
```

`sudo /usr/pgsql-9.3/bin/postgresql93-setup initdb` works, though is not in anyones path, so not sure how to cleanly merge that into the code, or what versions of postgres it would be used for.
https://github.com/hw-cookbooks/postgresql/blob/43f0945bf525fbb81d5d5557fefb83cc5675ff85/recipes/server_redhat.rb#L78-L90

```
           - create new file /etc/sysconfig/pgsql/postgresql-9.3[2014-10-05T14:55:01+00:00] INFO: template[/etc/sysconfig/pgsql/postgresql-9.3] updated file contents /etc/sysconfig/pgsql/postgresql-9.3

           - update content in file /etc/sysconfig/pgsql/postgresql-9.3 from none to 3359a0
           --- /etc/sysconfig/pgsql/postgresql-9.3  2014-10-05 14:55:01.983335521 +0000
           +++ /tmp/chef-rendered-template20141005-10645-ocu22x 2014-10-05 14:55:01.983335521 +0000
           @@ -1 +1,3 @@
           +PGDATA=/var/lib/pgsql/9.3/data
           +PGPORT=5432[2014-10-05T14:55:01+00:00] INFO: template[/etc/sysconfig/pgsql/postgresql-9.3] mode changed to 644

           - change mode from '' to '0644'

           - restore selinux security context
         * execute[/sbin/service postgresql-9.3 initdb ] action run[2014-10-05T14:55:02+00:00] INFO: Processing execute[/sbin/service postgresql-9.3 initdb ] action run (postgresql::server_redhat line 86)


           ================================================================================
           Error executing action `run` on resource 'execute[/sbin/service postgresql-9.3 initdb ]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '2'
           ---- Begin output of /sbin/service postgresql-9.3 initdb  ----
           STDOUT: 
           STDERR: The service command supports only basic LSB actions (start, stop, restart, try-restart, reload, force-reload, status). For other actions, please try to use systemctl.
           ---- End output of /sbin/service postgresql-9.3 initdb  ----
           Ran /sbin/service postgresql-9.3 initdb  returned 2

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/postgresql/recipes/server_redhat.rb

            86:   execute "/sbin/service #{svc_name} initdb #{initdb_locale}" do
            87:     not_if { ::FileTest.exist?(File.join(dir, "PG_VERSION")) }
            88:   end
            89: 

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/postgresql/recipes/server_redhat.rb:86:in `from_file'

           execute("/sbin/service postgresql-9.3 initdb ") do
             action "run"
             retries 0
             retry_delay 2
             guard_interpreter :default
             command "/sbin/service postgresql-9.3 initdb "
             backup 5
             returns 0
             cookbook_name "postgresql"
             recipe_name "server_redhat"
             not_if { #code block }
           end

       [2014-10-05T14:55:02+00:00] INFO: Running queued delayed notifications before re-raising exception
       [2014-10-05T14:55:02+00:00] INFO: template[/etc/sysconfig/pgsql/postgresql-9.3] sending restart action to service[postgresql] (delayed)
         * service[postgresql] action restart[2014-10-05T14:55:02+00:00] INFO: Processing service[postgresql] action restart (postgresql::server_redhat line 92)


           ================================================================================
           Error executing action `restart` on resource 'service[postgresql]'
           ================================================================================

           Chef::Exceptions::Exec
           ----------------------
           /bin/systemctl restart postgresql-9.3 returned 1, expected 0

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/postgresql/recipes/server_redhat.rb

            92: service "postgresql" do
            93:   service_name svc_name
            94:   supports :restart => true, :status => true, :reload => true
            95:   action [:enable, :start]
            96: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/postgresql/recipes/server_redhat.rb:92:in `from_file'

           service("postgresql") do
             provider Chef::Provider::Service::Systemd
             action [:enable, :start]
             supports {:restart=>true, :status=>true, :reload=>true}
             retries 0
             retry_delay 2
             guard_interpreter :default
             service_name "postgresql-9.3"
             pattern "postgresql"
             cookbook_name "postgresql"
             recipe_name "server_redhat"
           end


       Running handlers:
       [2014-10-05T14:55:02+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2014-10-05T14:55:02+00:00] ERROR: Exception handlers complete
       [2014-10-05T14:55:02+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 37 resources updated in 592.055884004 seconds
       [2014-10-05T14:55:02+00:00] ERROR: Chef::Exceptions::MultipleFailures
       [2014-10-05T14:55:02+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <java-app-centos-70>.
>>>>>> Please see .kitchen/logs/java-app-centos-70.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sudo -E chef-client -z --config /tmp/kitchen/client.rb --log_level info --json-attributes /tmp/kitchen/dna.json]
>>>>>> ----------------------
```

**Comment by andre1810** [comment]
Got the same issue in 3.4.12 on CentOS 7 with pg 9.3 and enabled pgdg_yum.

**Comment by Odaeus** [comment]
Just come across this issue while trying to install PostgreSQL 9.3 on CentOS 7 with cookbook version 3.4.14. The [code path](https://github.com/hw-cookbooks/postgresql/blob/develop/recipes/server_redhat.rb#L58) for determining which `initdb` command to run doesn't appear to support CentOS? There's also no way to override it so I think I'll have to fork and modify the cookbook directly. Please let me know if you have a solution.

**Comment by mrjcleaver** [comment]
I just encounter the same, again, CentOS:
```
servername   * execute[/sbin/service postgresql-9.3 initdb ] action run
servername     
servername     ================================================================================
servername     Error executing action `run` on resource 'execute[/sbin/service postgresql-9.3 initdb ]'
servername     ================================================================================
servername     
servername     Mixlib::ShellOut::ShellCommandFailed
servername     ------------------------------------
servername     Expected process to exit with [0], but received '2'
servername     ---- Begin output of /sbin/service postgresql-9.3 initdb  ----
servername     STDOUT: 
servername     STDERR: The service command supports only basic LSB actions (start, stop, restart, try-restart, reload, force-reload, status). For other actions, please try to use systemctl.
servername     ---- End output of /sbin/service postgresql-9.3 initdb  ----
servername     Ran /sbin/service postgresql-9.3 initdb  returned 2
servername     
servername     Resource Declaration:
servername     ---------------------
servername     # In /var/chef/cache/cookbooks/postgresql/recipes/server_redhat.rb
servername     
servername      83:   execute "/sbin/service #{svc_name} initdb #{initdb_locale}" do
servername      84:     not_if { ::FileTest.exist?(File.join(dir, "PG_VERSION")) }
servername      85:   end
servername      86: 
servername     
servername     Compiled Resource:
servername     ------------------
servername     # Declared in /var/chef/cache/cookbooks/postgresql/recipes/server_redhat.rb:83:in `from_file'
servername     
servername     execute("/sbin/service postgresql-9.3 initdb ") do
servername       action [:run]
servername       retries 0
servername       retry_delay 2
servername       default_guard_interpreter :execute
servername       command "/sbin/service postgresql-9.3 initdb "
servername       backup 5
servername       returns 0
servername       declared_type :execute
servername       cookbook_name "postgresql"
servername       recipe_name "server_redhat"
servername       not_if { #code block }
server name     end
servername     

```

**Comment by nmtoken** [comment]
I have the same problem:
`sudo service postgresql-9.5 initdb
The service command supports only basic LSB actions (start, stop, restart, try-restart, reload, force-reload, status). For other actions, please try to use systemctl.
`
I have `CentOS Linux release 7.2.1511 (Core) `

**Comment by robmarano** [comment]
Anyone resolve this? I am seeing this on PG 9.5. Strange PG 9.6.1 not supported. Here is the output from min
```
==> default: [2016-12-06T10:55:15-05:00] INFO: template[/etc/systemd/system/postgresql.service] sending run action to execute[systemctl-reload] (immediate)
==> default:   * execute[systemctl-reload] action run
==> default: [2016-12-06T10:55:15-05:00] INFO: execute[systemctl-reload] ran successfully
==> default:
==> default:     - execute systemctl daemon-reload
==> default:   * execute[systemctl-reload] action nothing (skipped due to action :nothing)
==> default:   * execute[postgresql-setup initdb postgresql-9.5] action run
==> default:
==> default:
==> default:     ================================================================================
==> default:     Error executing action `run` on resource 'execute[postgresql-setup initdb postgresql-9.5]'
==> default:     ================================================================================
==> default:
==> default:     Errno::ENOENT
==> default:     -------------
==> default:     No such file or directory - postgresql-setup
==> default:
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/postgresql/recipes/server_redhat.rb
==> default:
==> default:     108:     execute "#{node['postgresql']['setup_script']} initdb #{svc_name}" do
==> default:     109:       not_if { ::File.exist?("#{node['postgresql']['config']['data_directory']}/PG_VERSION") }
==> default:     110:     end
==> default:     111:   end
==> default:
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /var/chef/cache/cookbooks/postgresql/recipes/server_redhat.rb:108:in `from_file'
==> default:
==> default:     execute("postgresql-setup initdb postgresql-9.5") do
==> default:       action [:run]
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :execute
==> default:       command "postgresql-setup initdb postgresql-9.5"
==> default:       backup 5
==> default:       returns 0
==> default:       declared_type :execute
==> default:       cookbook_name "postgresql"
==> default:       recipe_name "server_redhat"
==> default:       not_if { #code block }
==> default:     end
==> default:
==> default:     Platform:
==> default:     ---------
==> default:     x86_64-linux
==> default:
==> default:
==> default: [2016-12-06T10:55:15-05:00] INFO: Running queued delayed notifications before re-raising exception
==> default: [2016-12-06T10:55:15-05:00] INFO: template[/etc/systemd/system/postgresql.service] sending reload action to service[postgresql] (delayed)
==> default:   * service[postgresql] action reload
==> default:  (up to date)
==> default:
==> default: Running handlers:
==> default: [2016-12-06T10:55:15-05:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2016-12-06T10:55:15-05:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 14 resources updated in 01 minutes 31 seconds
==> default: [2016-12-06T10:55:15-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2016-12-06T10:55:15-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2016-12-06T10:55:15-05:00] ERROR: execute[postgresql-setup initdb postgresql-9.5] (postgresql::server_redhat line 108) had an error: Errno::ENOENT: No such file or directory - postgresql-setup
==> default: [2016-12-06T10:55:15-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by kaleemullah360** [comment]
in CentOS 7 (RHEL) initdb now works with absolute path.
so we need to specified absolute path of `postgresql96-setup` setup file
first locate this file, different path for different version. 

**for 9.6 it is** 
`sudo /usr/pgsql-9.6/bin/postgresql96-setup initdb`

will produce following output:

```
[centos@pm ~]$ sudo /usr/pgsql-9.6/bin/postgresql96-setup initdb
[sudo] password for centos: 
Initializing database ... OK
```
