### ISSUE TITLE
Unable to install 9.4 on Ubuntu

### ISSUE THREAD

**Issue by chadwilken** [sous-chefs/postgresql#342]
I have been trying to upgrade 9.3 to 9.4 on Ubuntu and keep getting errors while doing so. I have some some research and found the other issues. Im not sure if I'm experiencing the same issue as them. Here is my log output:

```
Mixlib::ShellOut::ShellCommandFailed: service[postgresql] (postgresql::server_debian line 26) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /sbin/start postgresql ----
STDOUT: 
STDERR: start: Unknown job: postgresql
---- End output of /sbin/start postgresql ----
Ran /sbin/start postgresql returned 1
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:289:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:276:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/mixin/shell_out.rb:66:in `shell_out_with_systems_locale!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/service/upstart.rb:165:in `start_service'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/service/upstart.rb:193:in `restart_service'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/service.rb:158:in `block in action_restart'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider.rb:175:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/service.rb:157:in `action_restart'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider.rb:144:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource.rb:596:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/runner.rb:73:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/runner.rb:81:in `block in run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/runner.rb:79:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/runner.rb:79:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/runner.rb:105:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/runner.rb:105:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/runner.rb:105:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource_collection/resource_list.rb:84:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource_collection/resource_list.rb:82:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/runner.rb:104:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/client.rb:668:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/client.rb:663:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/client.rb:663:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/client.rb:702:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/client.rb:280:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:258:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:223:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:211:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/solo.rb:301:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/solo.rb:290:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/solo.rb:290:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/solo.rb:269:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:50:in `load'
```

And the output from the terminal when running cook:

```
Recipe: postgresql::server_debian
  * service[postgresql] action restart

    ================================================================================
    Error executing action `restart` on resource 'service[postgresql]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /sbin/start postgresql ----
    STDOUT: 
    STDERR: start: Unknown job: postgresql
    ---- End output of /sbin/start postgresql ----
    Ran /sbin/start postgresql returned 1

    Resource Declaration:
    ---------------------
    # In /root/chef-solo/cookbooks-2/postgresql/recipes/server_debian.rb

     28: service "postgresql" do
     29:   service_name node['postgresql']['server']['service_name']
     30:   supports :restart => true, :status => true, :reload => true
     31:   action [:enable, :start]
     32: end
     33: 

    Compiled Resource:
    ------------------
    # Declared in /root/chef-solo/cookbooks-2/postgresql/recipes/server_debian.rb:28:in `from_file'

    service("postgresql") do
      action [:enable, :start]
      supports {:restart=>true, :status=>true, :reload=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "postgresql"
      pattern "postgresql"
      declared_type :service
      cookbook_name :postgresql
      recipe_name "server_debian"
    end
```

**Comment by slyness** [comment]
Unless you provide more context about how you are running the cookbook there is nothing here that can help determine where your issue arises. What platform are you using? Are you using a separate cookbook to define and manage your customized implementation? Are you setting any attributes? Which ones and what values? What cookbook version are you using? 
If you're able to provide more context it might be possible to help identify your issue.. Thanks.

**Comment by allaire** [comment]
@slyness 

postgresql cookbook v4 does not take into consideration the version attribute set in my role, and always install 9.3. This broke our server. ubuntu 14.04

**Comment by tacchino** [comment]
Anyone have a decent solution to this?

**Comment by tanner-bruce** [comment]
@tacchino @allaire Checkout the default attributes. Just specifying the version as 9.4 is not enough, you need to override all the attributes in that section.

This is based on the latest tag on master, not develop.

**Comment by tacchino** [comment]
@tanner-bruce Yep, thanks, that's the path I took. For anyone else getting here:

```
default['postgresql']['version'] = '9.4'
default['postgresql']['dir'] = "/etc/postgresql/#{node['postgresql']['version']}/main"
default['postgresql']['config']['data_directory'] = "/var/lib/postgresql/#{node['postgresql']['version']}/main"
default['postgresql']['config']['hba_file'] = "/etc/postgresql/#{node['postgresql']['version']}/main/pg_hba.conf"
default['postgresql']['config']['ident_file'] = "/etc/postgresql/#{node['postgresql']['version']}/main/pg_ident.conf"
default['postgresql']['config']['external_pid_file'] = "/var/run/postgresql/#{node['postgresql']['version']}-main.pid"
default['postgresql']['client']['packages'] = ["postgresql-client-#{node['postgresql']['version']}", "libpq-dev"]
default['postgresql']['server']['packages'] = ["postgresql-#{node['postgresql']['version']}"]
default['postgresql']['contrib']['packages'] = ["postgresql-contrib-#{node['postgresql']['version']}"]
```

**Comment by fceruti** [comment]
For anyone interested, I also needed to add
```
default['postgresql']['enable_pgdg_apt'] = true
```

**Comment by damacus** [comment]
Looks like a UX issue here. We're moving custom resources so it should be easier in the future. As a result this shouldn't be relevant in the future! 

Thanks
