### ISSUE TITLE
build-essential package is not installed using the ruby recipie

### ISSUE THREAD

**Issue by aried3r** [sous-chefs/postgresql#373]
There are quite a few issues about this already (the most popular being #212 with 92 comments), but all of them closed and referring to either old Chef or cookbooks versions, so I'm opening a new one, because there is already a lot of clutter in there. (Should this be unwanted, I'll of course close this and continue there.)

Some files have been simplified, for example the actual cookbook I wrote is *not* called `my-database-wrapper` since it's doing a bit more than that.

I'm running:
`knife solo cook user@host`
on OS X 10.12.1
with Chef 12.16.42
postgresql-cookbook 5.1.0
on a Ubuntu 16.04.1 LTS Server

Node JSON, postgresql config taken from #370, since 16.04.1 LTS is missing 9.3 packages and I wanted to use the latest version anyway.
```JSON
{
  "run_list": [
    "recipe[build-essential::default]",
    "recipe[my-database-wrapper]"
  ],
  "postgresql": {
    "config": {
      "dynamic_shared_memory_type": "sysv"
    },
    "version": "9.6",
    "dir": "/etc/postgresql/9.6/main",
    "client": {
      "packages": ["postgresql-client-9.6","libpq-dev"]
    },
    "server": {
      "packages": ["postgresql-9.6"]
    },
    "contrib": {
      "packages": ["postgresql-contrib-9.6"]
    }
  }
}
```
```Ruby
# my-database-wrapper default recipe
include_recipe 'postgresql::ruby'
include_recipe 'postgresql::server'
include_recipe 'postgresql::config_initdb'
include_recipe 'postgresql::config_pgtune'
```
and running the patch from #356.

<details>
 <summary>This is the stack trace</summary>

```
Recipe: postgresql::ruby
  * apt_package[postgresql-client-9.6] action install (up to date)
  * apt_package[libpq-dev] action install (up to date)
  * chef_gem[pg] action install

    ================================================================================
    Error executing action `install` on resource 'chef_gem[pg]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/chef/embedded/bin/gem install pg -q --no-rdoc --no-ri -v "0.19.0" ----
    STDOUT: Building native extensions.  This could take a while...
    STDERR: ERROR:  Error installing pg:
    	ERROR: Failed to build gem native extension.

        current directory: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/pg-0.19.0/ext
    /opt/chef/embedded/bin/ruby -r ./siteconf20161111-15475-q6ojjr.rb extconf.rb
    checking for pg_config... yes
    Using config values from /usr/bin/pg_config
    checking for libpq-fe.h... *** extconf.rb failed ***
    Could not create Makefile due to some reason, probably lack of necessary
    libraries and/or headers.  Check the mkmf.log file for more details.  You may
    need configuration options.

    Provided configuration options:
    	--with-opt-dir
    	--with-opt-include
    	--without-opt-include=${opt-dir}/include
    	--with-opt-lib
    	--without-opt-lib=${opt-dir}/lib
    	--with-make-prog
    	--without-make-prog
    	--srcdir=.
    	--curdir
    	--ruby=/opt/chef/embedded/bin/$(RUBY_BASE_NAME)
    	--with-pg
    	--without-pg
    	--enable-windows-cross
    	--disable-windows-cross
    	--with-pg-config
    	--without-pg-config
    	--with-pg_config
    	--without-pg_config
    	--with-pg-dir
    	--without-pg-dir
    	--with-pg-include
    	--without-pg-include=${pg-dir}/include
    	--with-pg-lib
    	--without-pg-lib=${pg-dir}/lib
    /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
    You have to install development tools first.
    	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:598:in `try_cpp'
    	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:1155:in `block in find_header'
    	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:953:in `block in checking_for'
    	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
    	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:320:in `open'
    	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
    	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:320:in `open'
    	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
    	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:952:in `checking_for'
    	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:1154:in `find_header'
    	from extconf.rb:54:in `<main>'

    To see why this extension failed to compile, please check the mkmf.log which can be found here:

      /opt/chef/embedded/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/pg-0.19.0/mkmf.log

    extconf failed, exit code 1

    Gem files will remain installed in /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/pg-0.19.0 for inspection.
    Results logged to /opt/chef/embedded/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/pg-0.19.0/gem_make.out
    ---- End output of /opt/chef/embedded/bin/gem install pg -q --no-rdoc --no-ri -v "0.19.0" ----
    Ran /opt/chef/embedded/bin/gem install pg -q --no-rdoc --no-ri -v "0.19.0" returned 1

    Cookbook Trace:
    ---------------
    /root/chef-solo/local-mode-cache/cache/cookbooks/postgresql/recipes/ruby.rb:80:in `rescue in from_file'
    /root/chef-solo/local-mode-cache/cache/cookbooks/postgresql/recipes/ruby.rb:21:in `from_file'
    /root/chef-solo/local-mode-cache/cache/cookbooks/my-database-wrapper/recipes/postgresql.rb:10:in `from_file'
    /root/chef-solo/local-mode-cache/cache/cookbooks/my-database-wrapper/recipes/default.rb:10:in `from_file'

    Resource Declaration:
    ---------------------
    # In /root/chef-solo/local-mode-cache/cache/cookbooks/postgresql/recipes/ruby.rb

     80:     chef_gem 'pg' do
     81:       compile_time true if respond_to?(:compile_time)
     82:     end
     83:   rescue Gem::Installer::ExtensionBuildError, Mixlib::ShellOut::ShellCommandFailed => e

    Compiled Resource:
    ------------------
    # Declared in /root/chef-solo/local-mode-cache/cache/cookbooks/postgresql/recipes/ruby.rb:80:in `rescue in from_file'

    chef_gem("pg") do
      package_name "pg"
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :chef_gem
      cookbook_name "postgresql"
      recipe_name "ruby"
      compile_time true
      gem_binary "/opt/chef/embedded/bin/gem"
    end

    Platform:
    ---------
    x86_64-linux

[2016-11-11T13:26:16+01:00] WARN: Failed to properly build pg gem. Forcing properly linking and retrying (omnibus fix)
  * execute[generate pg gem Makefile] action run

    ================================================================================
    Error executing action `run` on resource 'execute[generate pg gem Makefile]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of PATH=$PATH:/usr/pgsql-9.6/bin /opt/chef/embedded/bin/ruby extconf.rb ----
    STDOUT: checking for pg_config... yes
    STDERR: Using config values from /usr/bin/pg_config
    *** extconf.rb failed ***
    Could not create Makefile due to some reason, probably lack of necessary
    libraries and/or headers.  Check the mkmf.log file for more details.  You may
    need configuration options.

    Provided configuration options:
    	--with-opt-dir
    	--with-opt-include
    	--without-opt-include=${opt-dir}/include
    	--with-opt-lib
    	--without-opt-lib=${opt-dir}/lib
    	--with-make-prog
    	--without-make-prog
    	--srcdir=.
    	--curdir
    	--ruby=/opt/chef/embedded/bin/$(RUBY_BASE_NAME)
    	--with-pg
    	--without-pg
    	--enable-windows-cross
    	--disable-windows-cross
    	--with-pg-config
    	--without-pg-config
    	--with-pg_config
    	--without-pg_config
    	--with-pg-dir
    	--without-pg-dir
    	--with-pg-include
    	--without-pg-include=${pg-dir}/include
    	--with-pg-lib
    	--without-pg-lib=${pg-dir}/lib
    /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
    You have to install development tools first.
    	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:552:in `try_link0'
    	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:567:in `try_link'
    	from extconf.rb:53:in `<main>'
    ---- End output of PATH=$PATH:/usr/pgsql-9.6/bin /opt/chef/embedded/bin/ruby extconf.rb ----
    Ran PATH=$PATH:/usr/pgsql-9.6/bin /opt/chef/embedded/bin/ruby extconf.rb returned 1

    Cookbook Trace:
    ---------------
    /root/chef-solo/local-mode-cache/cache/cookbooks/postgresql/recipes/ruby.rb:119:in `rescue in rescue in from_file'
    /root/chef-solo/local-mode-cache/cache/cookbooks/postgresql/recipes/ruby.rb:79:in `rescue in from_file'
    /root/chef-solo/local-mode-cache/cache/cookbooks/postgresql/recipes/ruby.rb:21:in `from_file'
    /root/chef-solo/local-mode-cache/cache/cookbooks/my-database-wrapper/recipes/postgresql.rb:10:in `from_file'
    /root/chef-solo/local-mode-cache/cache/cookbooks/my-database-wrapper/recipes/default.rb:10:in `from_file'

    Resource Declaration:
    ---------------------
    # In /root/chef-solo/local-mode-cache/cache/cookbooks/postgresql/recipes/ruby.rb

    113:     lib_builder = execute 'generate pg gem Makefile' do
    114:       # [COOK-3490] pg gem install requires full path on RHEL
    115:       command "PATH=$PATH:/usr/pgsql-#{node['postgresql']['version']}/bin #{RbConfig.ruby} extconf.rb"
    116:       cwd ext_dir
    117:       action :nothing
    118:     end
    119:     lib_builder.run_action(:run)

    Compiled Resource:
    ------------------
    # Declared in /root/chef-solo/local-mode-cache/cache/cookbooks/postgresql/recipes/ruby.rb:113:in `rescue in rescue in from_file'

    execute("generate pg gem Makefile") do
      action [:nothing]
      retries 0
      retry_delay 2
      default_guard_interpreter :execute
      command "PATH=$PATH:/usr/pgsql-9.6/bin /opt/chef/embedded/bin/ruby extconf.rb"
      backup 5
      cwd "/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/pg-0.19.0/ext"
      returns 0
      declared_type :execute
      cookbook_name "postgresql"
      recipe_name "ruby"
    end

    Platform:
    ---------
    x86_64-linux


  ================================================================================
  Recipe Compile Error in /root/chef-solo/local-mode-cache/cache/cookbooks/my-database-wrapper/recipes/default.rb
  ================================================================================

  Mixlib::ShellOut::ShellCommandFailed
  ------------------------------------
  execute[generate pg gem Makefile] (postgresql::ruby line 113) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
  ---- Begin output of PATH=$PATH:/usr/pgsql-9.6/bin /opt/chef/embedded/bin/ruby extconf.rb ----
  STDOUT: checking for pg_config... yes
  STDERR: Using config values from /usr/bin/pg_config
  *** extconf.rb failed ***
  Could not create Makefile due to some reason, probably lack of necessary
  libraries and/or headers.  Check the mkmf.log file for more details.  You may
  need configuration options.

  Provided configuration options:
  	--with-opt-dir
  	--with-opt-include
  	--without-opt-include=${opt-dir}/include
  	--with-opt-lib
  	--without-opt-lib=${opt-dir}/lib
  	--with-make-prog
  	--without-make-prog
  	--srcdir=.
  	--curdir
  	--ruby=/opt/chef/embedded/bin/$(RUBY_BASE_NAME)
  	--with-pg
  	--without-pg
  	--enable-windows-cross
  	--disable-windows-cross
  	--with-pg-config
  	--without-pg-config
  	--with-pg_config
  	--without-pg_config
  	--with-pg-dir
  	--without-pg-dir
  	--with-pg-include
  	--without-pg-include=${pg-dir}/include
  	--with-pg-lib
  	--without-pg-lib=${pg-dir}/lib
  /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
  You have to install development tools first.
  	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:552:in `try_link0'
  	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:567:in `try_link'
  	from extconf.rb:53:in `<main>'
  ---- End output of PATH=$PATH:/usr/pgsql-9.6/bin /opt/chef/embedded/bin/ruby extconf.rb ----
  Ran PATH=$PATH:/usr/pgsql-9.6/bin /opt/chef/embedded/bin/ruby extconf.rb returned 1

  Cookbook Trace:
  ---------------
    /root/chef-solo/local-mode-cache/cache/cookbooks/postgresql/recipes/ruby.rb:119:in `rescue in rescue in from_file'
    /root/chef-solo/local-mode-cache/cache/cookbooks/postgresql/recipes/ruby.rb:79:in `rescue in from_file'
    /root/chef-solo/local-mode-cache/cache/cookbooks/postgresql/recipes/ruby.rb:21:in `from_file'
    /root/chef-solo/local-mode-cache/cache/cookbooks/my-database-wrapper/recipes/postgresql.rb:10:in `from_file'
    /root/chef-solo/local-mode-cache/cache/cookbooks/my-database-wrapper/recipes/default.rb:10:in `from_file'

  Relevant File Content:
  ----------------------
  /root/chef-solo/local-mode-cache/cache/cookbooks/postgresql/recipes/ruby.rb:

  112:
  113:      lib_builder = execute 'generate pg gem Makefile' do
  114:        # [COOK-3490] pg gem install requires full path on RHEL
  115:        command "PATH=$PATH:/usr/pgsql-#{node['postgresql']['version']}/bin #{RbConfig.ruby} extconf.rb"
  116:        cwd ext_dir
  117:        action :nothing
  118:      end
  119>>     lib_builder.run_action(:run)
  120:
  121:      lib_maker = execute 'make pg gem lib' do
  122:        command 'make'
  123:        cwd ext_dir
  124:        action :nothing
  125:      end
  126:      lib_maker.run_action(:run)
  127:
  128:      lib_installer = execute 'install pg gem lib' do

  Platform:
  ---------
  x86_64-linux


  Running handlers:
[2016-11-11T13:26:16+01:00] ERROR: Running exception handlers
  Running handlers complete
[2016-11-11T13:26:16+01:00] ERROR: Exception handlers complete
  Chef Client failed. 0 resources updated in 05 seconds
[2016-11-11T13:26:16+01:00] FATAL: Stacktrace dumped to /root/chef-solo/local-mode-cache/cache/chef-stacktrace.out
[2016-11-11T13:26:16+01:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-11-11T13:26:16+01:00] ERROR: execute[generate pg gem Makefile] (postgresql::ruby line 113) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of PATH=$PATH:/usr/pgsql-9.6/bin /opt/chef/embedded/bin/ruby extconf.rb ----
STDOUT: checking for pg_config... yes
STDERR: Using config values from /usr/bin/pg_config
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/chef/embedded/bin/$(RUBY_BASE_NAME)
	--with-pg
	--without-pg
	--enable-windows-cross
	--disable-windows-cross
	--with-pg-config
	--without-pg-config
	--with-pg_config
	--without-pg_config
	--with-pg-dir
	--without-pg-dir
	--with-pg-include
	--without-pg-include=${pg-dir}/include
	--with-pg-lib
	--without-pg-lib=${pg-dir}/lib
/opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:552:in `try_link0'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:567:in `try_link'
	from extconf.rb:53:in `<main>'
---- End output of PATH=$PATH:/usr/pgsql-9.6/bin /opt/chef/embedded/bin/ruby extconf.rb ----
Ran PATH=$PATH:/usr/pgsql-9.6/bin /opt/chef/embedded/bin/ruby extconf.rb returned 1
[2016-11-11T13:26:16+01:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR: RuntimeError: chef-solo failed. See output above.
```

</details>

<details>
  <summary>Content of the `/opt/chef/embedded/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/pg-0.19.0/mkmf.log` log file</summary>

```
find_executable: checking for pg_config... -------------------- yes

--------------------

"gcc -o conftest -I/opt/chef/embedded/include/ruby-2.3.0/x86_64-linux -I/opt/chef/embedded/include/ruby-2.3.0/ruby/backward -I/opt/chef/embedded/include/ruby-2.3.0 -I. -I/usr/include/postgresql -I/opt/chef/embedded/include -O2 -O3 -g -pipe -I/opt/chef/embedded/include   -I/opt/chef/embedded/include -O2 -O3 -g -pipe -fPIC conftest.c  -L. -L/opt/chef/embedded/lib -Wl,-R/opt/chef/embedded/lib -L/usr/lib/x86_64-linux-gnu -Wl,-R/usr/lib/x86_64-linux-gnu -L/opt/chef/embedded/lib -Wl,-R/opt/chef/embedded/lib -L. -Wl,-rpath,/opt/chef/embedded/lib -fstack-protector -L/opt/chef/embedded/lib -rdynamic -Wl,-export-dynamic -L/opt/chef/embedded/lib  -Wl,-R/opt/chef/embedded/lib     -Wl,-R/opt/chef/embedded/lib -L/opt/chef/embedded/lib -lruby  -lpthread -lrt -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

</details>

.
The TL;DR I gathered from #212 was that despite [these two lines](https://github.com/chef-brigade/postgresql-cookbook/blob/v5.1.0/recipes/ruby.rb#L32-L33) in the `ruby` recipe, Chef or this cookbook fails to install the build-essentials package at compile time (as [documented here](https://github.com/chef-cookbooks/build-essential#user-content-gems-with-c-extensions) and mentioned [here](https://github.com/chef-brigade/postgresql-cookbook/issues/212#issuecomment-75823761)) and thus gcc etc are missing (see also [this comment](https://github.com/chef-brigade/postgresql-cookbook/issues/212#issuecomment-75780877)).

Most people that _did_ get it working reported that a [workaround like this one](https://github.com/chef-brigade/postgresql-cookbook/issues/212#issuecomment-100101069) seems to work.

But I'd love to have this very old issue resolved by the cookbook itself. Is there anything missing or am I doing something wrong?

**Comment by tas50** [comment]
@aried3r What version of this cookbook are you using?

**Comment by aried3r** [comment]
> @aried3r What version of this cookbook are you using?

postgresql-cookbook 5.1.0

**Comment by aried3r** [comment]
Using this local setup I was able to reproduce the error. It strips away almost everything of what we do in our production setup but still displays the exact same behavior.
```JSON
{
  "name": "postgres-pg-issue",
  "run_list": [
    "recipe[build-essential::default]",
    "recipe[postgresql::ruby]",
    "recipe[postgresql::server]"
  ],
  "automatic": {
    "ipaddress": "localhost"
  }
}
```

```Ruby
# Vagrantfile

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Use Ubuntu 16.04 Xenial 64-bit LTS as our operating system
  config.vm.box = 'ubuntu/xenial64-daily'
  config.vm.box_url = 'https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-vagrant.box'
  config.vm.box_download_checksum = '027193ec2a9888c0b3970c9b2e01496041902e687724d6cb6520bcfd762487e7'
  config.vm.box_download_checksum_type = 'sha256'

  # Set the hostname
  config.vm.hostname = 'postgres-pg-box'

  # Configure the virtual machine
  config.vm.provider 'virtualbox' do |vb|
    cpus = case RbConfig::CONFIG['host_os']
      when /darwin/ then `sysctl -n hw.ncpu`.to_i
      when /linux/ then `nproc`.to_i
      else 2
    end

    # Customize memory in MB
    vb.customize ['modifyvm', :id, '--memory', 2048]
    vb.customize ['modifyvm', :id, '--cpus', cpus]
  end
end
```
```
vagrant up
knife solo prepare -i .vagrant/machines/default/virtualbox/private_key -p 2222 ubuntu@localhost
knife solo cook -i .vagrant/machines/default/virtualbox/private_key -p 2222 ubuntu@localhost
```

**Comment by aried3r** [comment]
Ok, I was on the right track after reading through #212 and finally found what I was doing wrong, but also (possibly?) found something that this cookbook can't fix itself, but will remain a usage-error.

After reading [this bug ticket](https://tickets.opscode.com/browse/COOK-2641?focusedCommentId=50481&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-50481), especially these paragraphs:
> Then it should be sufficient (and recommended!) to set the attribute in the attributes file of the wrapper cookbook.
> ...
> If two cookbooks call include_recipe "build-essential" it will get included the first time. If the second wrapper cookbook is the one setting the attribute then **it will set the attribute but the build-essentials cookbook will have already been compile-time evaluated and will be skipped**. Using the attribute file is probably more what you want since then all cookbooks who depend on the build-essentials cookbook will have all their attribute files evaluated before any cookbook compilation is done. **This way if you have one cookbook which doesn't care and one cookbook which forces compile-time**, then both attribute requirements will get evaluated irregardless of ordering. If you try to set this attribute at compile time, then you must include the cookbook which sets the compile-time variable first.

I think my mistake was that I included the `build-essential` cookbook myself and **not** setting the attribute in the `attributes.rb` file but in my recipe, thus the quoted behavior was observed.

What do you think @tas50, should the docs be updated to reflect this or should it already be clear? (But after reading #212 with 92 comments it seems it's not *that* clear.)

**Comment by damacus** [comment]
Hey @aried3r would you be able to give the pg_gem a bit of loving? I'm stuck fixing this issue due to #462

**Comment by aried3r** [comment]
Hey! Sorry for the late reply. Phew, it's been so long since I fixed that in our setup, I'll have to see what I did back then.

What exactly would you want me to do? :)

**Comment by damacus** [comment]
I think the latest version (master) of the cookbook should fix this exact error (build essentials), but the `pg_gem` resource isn't quite working right now. 

If you take a look at #462 it should give you a good idea where we are with the resource. 

Might be worth taking the conversation over to there about how we fix the resource generally?

**Comment by damacus** [comment]
Closing this in favour of tracking the pg_gem issue in #462
