### ISSUE TITLE
 user "postgres", database "template1", SSL off

### ISSUE THREAD

**Issue by tobymaro** [sous-chefs/postgresql#383]
Attribute node['gerrit']['database']['database'] has name 'reviewdb' But for some reason resource postgresql_database trying connect to "template1" . node['gerrit']['database']['hostname'] is remote database host.

```
postgresql_connection_info = {
    :host =>  node['gerrit']['database']['hostname'],
    :port =>  node['postgresql']['config']['port'],
    :username => "postgres",
    :password => node['postgresql']['password']['postgres']
  }
```

```
postgresql_database 'run script' do
    connection postgresql_connection_info
    sql { ::File.open(init_sql_my).read }
    database_name node['gerrit']['database']['database']
    action :query
  end

```

I get

```
 * postgresql_database[run script] action query

    ================================================================================
    Error executing action `query` on resource 'postgresql_database[run script]'
    ================================================================================

    PG::ConnectionBad
    -----------------
    FATAL:  no pg_hba.conf entry for host "10.244.129.175", user "postgres", database "template1", SSL off

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/database/libraries/provider_database_postgresql.rb:132:in `initialize'
    /var/chef/cache/cookbooks/database/libraries/provider_database_postgresql.rb:132:in `new'
    /var/chef/cache/cookbooks/database/libraries/provider_database_postgresql.rb:132:in `db'
    /var/chef/cache/cookbooks/database/libraries/provider_database_postgresql.rb:97:in `exists?'
    /var/chef/cache/cookbooks/database/libraries/provider_database_postgresql.rb:80:in `block in <class:Postgresql>'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/mygerrit/recipes/default.rb

     93:   postgresql_database 'run script' do
     94:     connection postgresql_connection_info
     95:     sql { ::File.open(init_sql_my).read }
     96:     database_name node['gerrit']['database']['database']
     97:     action :query
     98:   end
     99: end

```

**Comment by damacus** [comment]
I'm going to close this one down now as it's been a while and we've moved master to custom resources. 
This bug doesn't look reproducible with the given information. If you can reproduce it as a test case, we would *really appreciate* the PR
