### ISSUE TITLE
Extensions stopped to work

### ISSUE THREAD

**Issue by sauliusgrigaitis** [sous-chefs/postgresql#391]
Looks like latest extensions resource refactoring has an issue:

```
Recipe: postgresql::contrib
  * postgresql_extension[database_name/plpgsql] action createRecipe: postgresql::contrib
  * postgresql_extension[database_name/plpgsql] action create
    * bash[CREATE EXTENSION database_name/plpgsql] action run
    * bash[CREATE EXTENSION database_name/plpgsql] action run

      ================================================================================
      Error executing action `run` on resource 'bash[CREATE EXTENSION database_name/plpgsql]'
      ================================================================================

      ArgumentError
      -------------
      wrong number of arguments (given 0, expected 1)

      Cookbook Trace:
      ---------------
      /var/chef/cache/cookbooks/postgresql/resources/extension.rb:36:in `block (3 levels) in class_from_file'

      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/postgresql/resources/extension.rb

       32:   bash "CREATE EXTENSION #{name}" do
       33:     code psql("CREATE EXTENSION IF NOT EXISTS \"#{extension}\"")
       34:     user 'postgres'
       35:     action :run
       36:     not_if { installed? }
       37:   end
       38: end

      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/postgresql/resources/extension.rb:32:in `block in class_from_file'

      bash("CREATE EXTENSION database_name/plpgsql") do
        action [:run]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        command "CREATE EXTENSION database_name/plpgsql"
        backup 5
        returns 0
        user "postgres"
        code "psql -d database_name <<< '\\set ON_ERROR_STOP on\nCREATE EXTENSION IF NOT EXISTS \"plpgsql\";'"
        interpreter "bash"
        declared_type :bash
        cookbook_name "postgresql"
        not_if { #code block }
      end

      Platform:
      ---------
      x86_64-linux-gnu

    ================================================================================
    Error executing action `create` on resource 'postgresql_extension[database_name/plpgsql]'
    ================================================================================

    ArgumentError
    -------------
    bash[CREATE EXTENSION database_name/plpgsql] (/var/chef/cache/cookbooks/postgresql/resources/extension.rb line 32) had an error: ArgumentError: wrong number of arguments (given 0, expected 1)

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/postgresql/resources/extension.rb:36:in `block (3 levels) in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/postgresql/recipes/contrib.rb

     32:     postgresql_extension "#{db_name}/#{pg_ext}"
     33:   end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/postgresql/recipes/contrib.rb:32:in `block in from_file'

    postgresql_extension("database_name/plpgsql") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :postgresql_extension
      cookbook_name "postgresql"
      recipe_name "contrib"
      extension "plpgsql"
      database "database_name"
    end

    Platform:
    ---------
    x86_64-linux-gnu
```
I'm using latest Chef 12.17.44.

**Comment by tas50** [comment]
I'll take a look at this. Sorry for the breakage

**Comment by tas50** [comment]
@sauliusgrigaitis Can you give me a bit more detail on the problem? I'm trying to reproduce it, but I can't get it to fail. I expanded the contrib test suite in Test Kitchen to install 2 extensions and they run fine.

https://github.com/sous-chefs/postgresql/pull/393/

What platform?
What Postgresql version?
What Chef version?
What attributes are you setting?

**Comment by sauliusgrigaitis** [comment]
It's latest stable Ubuntu 16.04 LTS, PostgreSQL 9.6, attributes:

```
"postgresql": {
    "config": {
      "dynamic_shared_memory_type": "sysv"
    },
    "database_name": "database_name",
    "version": "9.6",
    "dir": "/etc/postgresql/9.6/main",
    "client": {
      "packages": ["postgresql-client-9.6","libpq-dev"]
    },
    "server": {
      "packages": ["postgresql-9.6"]
    },
    "contrib": {
      "packages": ["postgresql-contrib-9.6"],
      "extensions": ["plpgsql"]
    },
    "password": {
      "postgres": "..."
    },
    "config": {
      "listen_addresses": "..."
    },
    "pg_hba": [...]
  }
```
Workaround is to lock this cookbook version at `d4c1bf2`.

**Comment by rapcal** [comment]
Second the issue and the workaround with a similar config: Ubuntu 16.04 LTS & PostgreSQL 9.6.
Locking on d4c1bf20c007b1b6c4af6a5cd57537dab073ca4a is what fixed the issue.
Thanks, @sauliusgrigaitis!

**Comment by teknofire** [comment]
I get this same problem when including `chef-sugar` into the run.  Take that out and the system is able to converge fine.  Probably has to do with the `installed?` method they define that gets injected into the Chef::Resource or Chef::Provider classes

https://github.com/sethvargo/chef-sugar/blob/becff20f0c775fbb753258f1c3311696db639033/lib/chef/sugar/shell.rb#L134

**Comment by sauliusgrigaitis** [comment]
@teknofire I also have ```chef-sugar``` as a dependency of cookbook I use.

**Comment by allaire** [comment]
Having the same issue, chef-sugar is required by `firewall` cookbook
