### ISSUE TITLE
Parent directory /etc/postgresql/9.3/main does not exist (reprise)

### ISSUE THREAD

**Issue by gionn** [sous-chefs/postgresql#411]
### Cookbook version
6.0.1

### Chef-client version
12.6.0

### Platform Details
Ubuntu 14.04

### Scenario:
https://github.com/sous-chefs/postgresql/issues/108

### Steps to Reproduce:
```
include_recipe 'postgresql::ruby'
include_recipe 'postgresql::contrib'
include_recipe 'postgresql::server'
```

### Actual Result:
```
       Recipe: postgresql::server_debian
         * apt_package[postgresql-9.3] action install
           - install version 9.3.15-0ubuntu0.14.04 of package postgresql-9.3
       Recipe: postgresql::server_conf
         * template[/etc/postgresql/9.3/main/postgresql.conf] action create
           * Parent directory /etc/postgresql/9.3/main does not exist.
           ================================================================================
           Error executing action `create` on resource 'template[/etc/postgresql/9.3/main/postgresql.conf]'
           ================================================================================
           
           Chef::Exceptions::EnclosingDirectoryDoesNotExist
           ------------------------------------------------
           Parent directory /etc/postgresql/9.3/main does not exist.
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
           /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
           /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
           /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
           /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
```

**Comment by gionn** [comment]
This won't happen if I include the locale cookbook in the run_list, hence configuring locale is a requirement for debian platform for this cookbook, and should be documented?

Otherwise, If a locale is not present at run-time, the server recipe for debian platform could simply fail and prevent such error (`Parent directory /etc/postgresql/9.3/main does not exist.`) that doesn't really mean anything to the user running this cookbook.

**Comment by damacus** [comment]
I'll add a 9.3 test to this cookbook to cover this in the future.

I'm not seeing this behaviour on debian 9

**Comment by damacus** [comment]
This is now covered by test cases in master, and actually fails travis when/if it regresses.
