### ISSUE TITLE
postgresql_extension throws SQL error

### ISSUE THREAD

**Issue by xparabolax** [sous-chefs/postgresql#541]
### Cookbook version
7.0.0

### Chef-client version
14.2.0

### Platform Details
Vagrant -> Ubuntu 18.04

### Scenario:
Attempting to run the following recipe:

```
postgresql_server_install 'server_install' do
  version node['postgresql']['version']
  password node['db']['database_password']
  action :install
end

postgresql_user node['db']['database_user'] do
  password node['db']['database_password']
end

postgresql_user 'postgres' do
  password node['postgresql']['password']['postgres']
  superuser true
  action :update
end

postgresql_access 'postgresql host superuser' do
  access_type 'host'
  access_db 'all'
  access_user 'postgres'
  access_addr '127.0.0.1/32'
  access_method 'md5'
  notifies :reload, 'service[postgresql]'
end

postgresql_access node['db']['database_user'] do
  access_type 'host'
  access_db node['db']['database_name']
  access_user node['db']['database_user']
  access_addr '127.0.0.1/32'
  access_method 'md5'
  notifies :reload, 'service[postgresql]'
end

ENV['PGPASSWORD'] = node['db']['database_password']

postgresql_database node['db']['database_name'] do
  host '127.0.0.1'
  port node['db']['database_port']
  template 'template0'
  action :create
end

postgresql_extension 'uuid-ossp' do
  database node['db']['database_name']
end

service 'postgresql' do
  extend PostgresqlCookbook::Helpers
  service_name lazy { platform_service_name }
  supports restart: true, status: true, reload: true
  action :nothing
end
```

fails with result
```
==> default: [2018-06-12T21:12:23+00:00] FATAL: psql failed executing this SQL statement:
==> default: SELECT 'installed' FROM pg_extension WHERE extname = 'uuid-ossp';

...
==> default:       ================================================================================
==> default:       Error executing action `run` on resource 'bash[CREATE EXTENSION uuid-ossp]'
==> default:       ================================================================================
==> default:
==> default:       RuntimeError
==> default:       ------------
==> default:       SQL ERROR
==> default:
==> default:       Cookbook Trace:
==> default:       ---------------
==> default:       /var/chef/cache/cookbooks/postgresql/libraries/helpers.rb:45:in `execute_sql'
==> default:       /var/chef/cache/cookbooks/postgresql/libraries/helpers.rb:96:in `extension_installed?'
==> default:       /var/chef/cache/cookbooks/postgresql/resources/extension.rb:30:in `block (3 levels) in class_from_file'
==> default:
==> default:       Resource Declaration:
==> default:       ---------------------
==> default:       # In /var/chef/cache/cookbooks/postgresql/resources/extension.rb
==> default:
==> default:        26:   bash "CREATE EXTENSION #{new_resource.name}" do
==> default:        27:     code psql_command_string(new_resource.database, create_query)
==> default:        28:     user 'postgres'
==> default:        29:     action :run
==> default:        30:     not_if { slave? || extension_installed? }
==> default:        31:   end
==> default:        32: end
==> default:
==> default:       Compiled Resource:
==> default:       ------------------
==> default:       # Declared in /var/chef/cache/cookbooks/postgresql/resources/extension.rb:26:in `block in class_from_file'
==> default:
==> default:       bash("CREATE EXTENSION uuid-ossp") do
==> default:         action [:run]
==> default:         default_guard_interpreter :default
==> default:         command nil
==> default:         backup 5
==> default:         interpreter "bash"
==> default:         declared_type :bash
==> default:         cookbook_name "application"
==> default:         code "psql -d database_name <<< '\\set ON_ERROR_STOP on\nCREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";'"
==> default:         user "postgres"
==> default:         domain nil
==> default:         not_if { #code block }
==> default:       end
==> default:
==> default:       System Info:
==> default:       ------------
==> default:       chef_version=14.2.0
==> default:       platform=ubuntu
==> default:       platform_version=18.04
==> default:       ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
==> default:       program_name=/usr/bin/chef-solo
==> default:       executable=/opt/chef/bin/chef-solo

```

Expected the extension to be installed, but instead provisioning halts with the error.

**Comment by zeroedin** [comment]
Running into a similar error using 9.6 and hstore.

**Comment by damacus** [comment]
Yeah this is super broken right now check #535 for progress on this. I've made some heavy refactors and improvements in testing and general "things working"
