### ISSUE TITLE
You must supply a name when declaring a apt_update resource

### ISSUE THREAD

**Issue by obazoud** [sous-chefs/postgresql#558]
### Cookbook version
7.1.0
Works fine in 7.0.0

### Chef-client version
12.22.3

### Platform Details
Ubuntu 18.04 LTS on AWS

### Scenario:
Works ;)

### Actual Result:

```
[2018-09-01T21:49:36+00:00] INFO: Running queued delayed notifications before re-raising exception
    
    ================================================================================
    Error executing action `install` on resource 'postgresql_client_install[My Postgresql Client install]'
    ================================================================================
    
    ArgumentError
    -------------
    postgresql_repository[Add downloads.postgresql.org repository] (/var/chef/cache/cookbooks/postgresql/resources/client_install.rb line 23) had an error: ArgumentError: You must supply a name when declaring a apt_update resource
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/postgresql/resources/repository.rb:72:in `block in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/xxx-backup/recipes/rds.rb
    
     10:   postgresql_client_install 'My Postgresql Client install' do
     11:     version '9.6'
     12:   end
     13: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/xxx-backup/recipes/rds.rb:10:in `from_file'
    
    postgresql_client_install("My Postgresql Client install") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :postgresql_client_install
      cookbook_name "xxx-backup"
      recipe_name "rds"
      version "9.6"
    end
    
    System Info:
    ------------
    chef_version=12.22.3
    platform=ubuntu
    platform_version=18.04
    ruby=ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-linux]
    program_name=chef-client worker: ppid=9184;start=21:49:00;
    executable=/opt/chef/bin/chef-client
```

**Comment by obazoud** [comment]
Ok but:
- should be 8.0 not 7.1
- should be written in changelog

**Comment by waltercool** [comment]
I do agree, making an undocumented breaking change on a minor version is not okay.

**Comment by yacn** [comment]
I too love making breaking changes in a minor version and telling affected users to get stuffed.

**Comment by josephholsten** [comment]
turns out that the minimum chef requirement of this release of the cookbook was `chef_version      '>= 13.8'`, so this was communicated as best we knew how: https://github.com/sous-chefs/postgresql/commit/047539d2e0001eca72466858124ea3cc4a8813f6#diff-9fd042d4cd1e8f82894bbd7dffb313ec

I'd absolutely love advice on how we can express these requirements better in the future.
