### ISSUE TITLE
7.1.1 broke test kitchen for me

### ISSUE THREAD

**Issue by jquick** [sous-chefs/postgresql#568]
Error:
```
E, [2018-09-27T17:15:31.409559 #30991] ERROR -- default-ubuntu-1604: Message: Docker Exec (1) for command: [/opt/chef/embedded/bin/chef-client -z -l warn -F doc -c /opt/kitchen/client.rb -j /opt/kitchen/dna.json]
E, [2018-09-27T17:15:31.409579 #30991] ERROR -- default-ubuntu-1604: ----------------------
E, [2018-09-27T17:15:31.409599 #30991] ERROR -- default-ubuntu-1604: ------Backtrace-------
E, [2018-09-27T17:15:31.409618 #30991] ERROR -- default-ubuntu-1604: /Users/jquick/.gem/ruby/2.4.3/gems/kitchen-dokken-2.6.7/lib/kitchen/provisioner/dokken.rb:59:in `rescue in call'
E, [2018-09-27T17:15:31.409643 #30991] ERROR -- default-ubuntu-1604: /Users/jquick/.gem/ruby/2.4.3/gems/kitchen-dokken-2.6.7/lib/kitchen/provisioner/dokken.rb:62:in `call'
E, [2018-09-27T17:15:31.409682 #30991] ERROR -- default-ubuntu-1604: /Users/jquick/.gem/ruby/2.4.3/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:408:in `block in converge_action'
E, [2018-09-27T17:15:31.409728 #30991] ERROR -- default-ubuntu-1604: /Users/jquick/.gem/ruby/2.4.3/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:551:in `synchronize_or_call'
E, [2018-09-27T17:15:31.409755 #30991] ERROR -- default-ubuntu-1604: /Users/jquick/.gem/ruby/2.4.3/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:513:in `block in action'
E, [2018-09-27T17:15:31.409775 #30991] ERROR -- default-ubuntu-1604: /Users/jquick/.rubies/ruby-2.4.3/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2018-09-27T17:15:31.409808 #30991] ERROR -- default-ubuntu-1604: /Users/jquick/.gem/ruby/2.4.3/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:512:in `action'
E, [2018-09-27T17:15:31.409831 #30991] ERROR -- default-ubuntu-1604: /Users/jquick/.gem/ruby/2.4.3/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:404:in `converge_action'
E, [2018-09-27T17:15:31.409847 #30991] ERROR -- default-ubuntu-1604: /Users/jquick/.gem/ruby/2.4.3/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
E, [2018-09-27T17:15:31.409866 #30991] ERROR -- default-ubuntu-1604: /Users/jquick/.gem/ruby/2.4.3/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
E, [2018-09-27T17:15:31.409881 #30991] ERROR -- default-ubuntu-1604: /Users/jquick/.gem/ruby/2.4.3/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2018-09-27T17:15:31.409895 #30991] ERROR -- default-ubuntu-1604: /Users/jquick/.gem/ruby/2.4.3/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `each'
E, [2018-09-27T17:15:31.409910 #30991] ERROR -- default-ubuntu-1604: /Users/jquick/.gem/ruby/2.4.3/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `transition_to'
E, [2018-09-27T17:15:31.409924 #30991] ERROR -- default-ubuntu-1604: /Users/jquick/.gem/ruby/2.4.3/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:162:in `verify'
E, [2018-09-27T17:15:31.409939 #30991] ERROR -- default-ubuntu-1604: /Users/jquick/.gem/ruby/2.4.3/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:191:in `block in test'
E, [2018-09-27T17:15:31.409953 #30991] ERROR -- default-ubuntu-1604: /Users/jquick/.rubies/ruby-2.4.3/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2018-09-27T17:15:31.409968 #30991] ERROR -- default-ubuntu-1604: /Users/jquick/.gem/ruby/2.4.3/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:187:in `test'
E, [2018-09-27T17:15:31.409984 #30991] ERROR -- default-ubuntu-1604: /Users/jquick/.gem/ruby/2.4.3/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `public_send'
E, [2018-09-27T17:15:31.410010 #30991] ERROR -- default-ubuntu-1604: /Users/jquick/.gem/ruby/2.4.3/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2018-09-27T17:15:31.410043 #30991] ERROR -- default-ubuntu-1604: /Users/jquick/.gem/ruby/2.4.3/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
```

Pining back to 7.1.0 fixes the issue

**Comment by damacus** [comment]
Is this the full error?

**Comment by damacus** [comment]
Can you update your ChefDK and report back. Closing for now as this has been open for 2 months without activity.
