### ISSUE TITLE
uninitialized constant #<Class:0x00007f3d9ecc4e70>::PostgresqlCookbook

### ISSUE THREAD

**Issue by krisdigital** [sous-chefs/postgresql#738]
### :speaking_head: Foreword

Hello! I am having a hard time finding the reason for this error when converging, without even using a postgresql resource!
Other cookbooks are working normally.

I tried with my virtual server running Ubuntu 22.04 and also with a vagrant box to be sure, then again with Ubuntu 20.04

`uninitialized constant #<Class:0x00007f3d9ecc4e70>::PostgresqlCookbook`

## :ghost: Brief Description

It seems to me that there is something wrong with generating the class name?

```
Cookbook Trace: (most recent call first)
 ----------------------------------------
   /var/chef/cache/cookbooks/postgresql/resources/repository.rb:89:in `block in class_from_file'
   /var/chef/cache/cookbooks/postgresql/resources/repository.rb:88:in `class_from_file'
 
 Relevant File Content:
 ----------------------
 /var/chef/cache/cookbooks/postgresql/resources/repository.rb:
 
  82:      end
  83:    else
  84:      raise "The platform_family '#{node['platform_family']}' or platform '#{node['platform']}' is not supported by the postgresql_repository resource. If you believe this platform can/should be supported by this resource please file and issue or open a pull request at https://github.com/sous-chefs/postgresql"
  85:    end
  86:  end
  87:  
  88:  action_class do
  89>>   include PostgresqlCookbook::Helpers
  90:  end
  91:  
```

## :pancakes: Cookbook version

11.2.8

## :woman_cook:  Chef-Infra Version

18.2.7

## :tophat: Platform details

Ubuntu 22.04 or 20.04

## Steps To Reproduce

1. Add `cookbook 'postgresql', '~> 11.2.8'` to berksfile
2. Add `depends 'postgresql'` to `metadata.rb`
3. Converge any receipt, does not need to use postgres `knife zero converge "name:dev.vagrantbox.com" -U vagrant --override-runlist random`

## :police_car: Expected behavior

Error should not occur...

## :heavy_plus_sign: Additional context

I am using `knife zero`

**Comment by krisdigital** [comment]
Not sure what it was, but I started from scratch and it works 🤷‍♂️🥳
